# Generated by Django 4.1.2 on 2022-11-20 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('desc', models.TextField(blank=True, verbose_name='description')),
                ('bid', models.IntegerField(default=0, verbose_name='bid')),
                ('img', models.TextField(blank=True, default='', verbose_name='image')),
                ('owner', models.UUIDField(default='', verbose_name='id')),
                ('running', models.BooleanField(default=True, verbose_name='running')),
            ],
        ),
    ]
