# Generated by Django 4.1.2 on 2022-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.UUIDField(default='', verbose_name='owner_id'),
        ),
    ]
