# Generated by Django 4.1.2 on 2022-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.IntegerField(default='', verbose_name='owner_id'),
        ),
    ]
