# Generated by Django 4.1.2 on 2022-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_highestbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highestBid',
        ),
        migrations.AddField(
            model_name='product',
            name='highestBidder',
            field=models.IntegerField(default=0, verbose_name='highest_bidder'),
        ),
    ]
