# Generated by Django 4.1.2 on 2022-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_highestbid_product_highestbidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previousOwner',
            field=models.IntegerField(default=0, verbose_name='previous_owner'),
        ),
    ]
