# Generated by Django 4.1.2 on 2022-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_previousowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highestBidder',
            field=models.IntegerField(default=1, verbose_name='highest_bidder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='owner_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='previousOwner',
            field=models.IntegerField(default=2, verbose_name='previous_owner'),
        ),
    ]
