# Generated by Django 4.1.2 on 2022-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
